name: Sync to Secondary Repository

on:
  push:
    branches:
      - main  # Trigger this action on the main branch (change if needed)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "AmanSufian"
          git config --global user.email "amansufian04@gmail.com"

      - name: Push to Secondary Repository
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote add secondary https://$TOKEN@github.com/AmanSufian/Y1-SECPH-02
          git push secondary main --force
